### ISSUE TITLE
excuse me, how can I get pkl files?

### ISSUE THREAD

**Issue by s1162276945** [ewrfcas/DeMeshNet#1]
train_dict.pkl file is lost.

**Comment by ewrfcas** [comment]
It has no effect for the training, and it is just used to split the train and test data.

**Comment by quuhua911** [comment]
Traceback (most recent call last):
  File "train_segnet.py", line 12, in <module>
    with open('dataset/train_dict.pkl','rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/train_dict.pkl'

Is there an example file 　for train_dict.pkl
